export enum EventLocationEnumType {
  GOOGLE_MEET_AND_CALENDAR = 'GOOGLE_MEET_AND_CALENDAR',
  ZOOM_MEETING = 'ZOOM_MEETING',
  OUTLOOK_WITH_ZOOM = 'OUTLOOK_WITH_ZOOM', 
  OUTLOOK_WITH_TEAMS = 'OUTLOOK_WITH_TEAMS',
}